version: "3.9"

services:
  traefik:
    image: traefik:v3.0
    extra_hosts:
      - "host.docker.internal:host-gateway"
    container_name: traefik
    command:
      - "--providers.file.directory=/etc/traefik/dynamic"
      - "--providers.file.watch=true"
      - "--entrypoints.web.address=:80"
      - "--api.dashboard=true"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/dynamic.yml:/etc/traefik/dynamic/dynamic.yml:ro
    networks:
      - app-net

  redis:
    image: redis:7.0
    container_name: redis
    ports:
      - "6379:6379"

networks:
  app-net:
    driver: bridge
