http:
  routers:
    backend-router:
      rule: PathPrefix(`/`)
      service: backend-service
      entryPoints:
        - web

  services:
    backend-service:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: "http://host.docker.internal:8081"